name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 3: Install Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Step 4: Install ChromeDriver
    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromium-chromedriver
        # Remove existing chromedriver symlink or file if it exists
        sudo rm -f /usr/bin/chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    # Step 5: Set up xvfb (required for GUI-based testing in headless environments)
    - name: Set up xvfb
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        nohup Xvfb :99 -ac &

    # Step 6: Build with Maven and run TestNG tests using testng.xml
    - name: Run Maven TestNG Tests
      run: mvn -B test -DsuiteXmlFile=testng.xml --file pom.xml

   
